import React, { useEffect, useRef } from 'react';
import { User, Sparkles, Image as ImageIcon } from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { Prism as SyntaxHighlighter } from 'react-syntax-highlighter';
import { vscDarkPlus } from 'react-syntax-highlighter/dist/esm/styles/prism';
import './ChatHistory.css';

const ChatHistory = ({ messages, isLoading }) => {
    const messagesEndRef = useRef(null);

    const scrollToBottom = () => {
        messagesEndRef.current?.scrollIntoView({ behavior: 'smooth' });
    };

    useEffect(() => {
        scrollToBottom();
    }, [messages, isLoading]);

    return (
        <div className="chat-history-container">
            {messages.length === 0 ? (
                <div className="welcome-screen">
                    <div className="welcome-header">
                        <h1 className="text-gradient">Hello there.</h1>
                        <h2>How can KIA AI help you today?</h2>
                    </div>
                    <div className="suggestion-cards">
                        <div className="suggestion-card">
                            <Sparkles size={24} className="icon text-gradient" />
                            <p>Write a poem about the ocean</p>
                        </div>
                        <div className="suggestion-card">
                            <ImageIcon size={24} className="icon" style={{ color: '#d96570' }} />
                            <p>Generate an image of a futuristic city</p>
                        </div>
                        <div className="suggestion-card">
                            <Sparkles size={24} className="icon" style={{ color: '#4285f4' }} />
                            <p>Explain quantum computing to a child</p>
                        </div>
                    </div>
                </div>
            ) : (
                <div className="messages-wrapper">
                    {messages.map((message, index) => (
                        <div key={index} className={`message-row ${message.sender}`}>
                            <div className="avatar">
                                {message.sender === 'user' ? (
                                    <User size={20} />
                                ) : (
                                    <Sparkles size={16} color="#ffffff" className="kia-icon" />
                                )}
                            </div>
                            <div className="message-content">
                                {message.type === 'text' ? (
                                    <div className="text-content markdown-body">
                                        <ReactMarkdown
                                            remarkPlugins={[remarkGfm]}
                                            components={{
                                                code({ node, inline, className, children, ...props }) {
                                                    const match = /language-(\w+)/.exec(className || '')
                                                    return !inline && match ? (
                                                        <SyntaxHighlighter
                                                            {...props}
                                                            children={String(children).replace(/\n$/, '')}
                                                            style={vscDarkPlus}
                                                            language={match[1]}
                                                            PreTag="div"
                                                            customStyle={{ borderRadius: '8px', margin: '12px 0' }}
                                                        />
                                                    ) : (
                                                        <code {...props} className={className}>
                                                            {children}
                                                        </code>
                                                    )
                                                }
                                            }}
                                        >
                                            {message.text}
                                        </ReactMarkdown>
                                    </div>
                                ) : (
                                    <div className="image-content">
                                        <img src={message.imageUrl} alt="Generated by KIA AI" />
                                    </div>
                                )}
                            </div>
                        </div>
                    ))}

                    {isLoading && (
                        <div className="message-row ai loading">
                            <div className="avatar">
                                <Sparkles size={16} color="#ffffff" className="kia-icon" />
                            </div>
                            <div className="message-content">
                                <div className="loading-indicator">
                                    <div className="dot"></div>
                                    <div className="dot"></div>
                                    <div className="dot"></div>
                                </div>
                            </div>
                        </div>
                    )}

                    <div ref={messagesEndRef} />
                </div>
            )}
        </div>
    );
};

export default ChatHistory;
